import { ToolConfig } from '../types/tool.types';

export const TOOLS: Record<string, ToolConfig> = {
  generate: {
    id: 'generate',
    name: 'Generate Image',
    description: 'Create images from text descriptions with multiple style controls.',
    icon: 'image',
    route: '/generate',
    category: 'generate',
    supportedModels: ['recraftv4', 'recraftv4_vector', 'recraftv4_pro', 'recraftv4_pro_vector', 'recraftv3', 'recraftv3_vector', 'recraftv2', 'recraftv2_vector'],
    creditsPerGeneration: 40,
    supportsPrompt: true,
    supportsFileUpload: false,
    supportsMask: false,
  },
  'image-to-image': {
    id: 'image-to-image',
    name: 'Image to Image',
    description: 'Create variations of an image using a prompt and structural reference.',
    icon: 'copy',
    route: '/edit/image-to-image',
    category: 'edit',
    supportedModels: ['recraftv4', 'recraftv4_vector', 'recraftv3', 'recraftv3_vector'],
    creditsPerGeneration: 40,
    supportsPrompt: true,
    supportsFileUpload: true,
    supportsMask: false,
  },
  inpaint: {
    id: 'inpaint',
    name: 'Inpaint',
    description: 'Edit a specific masked region of an image using a text prompt.',
    icon: 'paintbrush',
    route: '/edit/inpaint',
    category: 'edit',
    supportedModels: ['recraftv4', 'recraftv3'],
    creditsPerGeneration: 40,
    supportsPrompt: true,
    supportsFileUpload: true,
    supportsMask: true,
  },
  'replace-background': {
    id: 'replace-background',
    name: 'Replace Background',
    description: 'Automatically detect and replace the background based on a prompt.',
    icon: 'layers',
    route: '/edit/replace-background',
    category: 'edit',
    supportedModels: ['recraftv4', 'recraftv3'],
    creditsPerGeneration: 40,
    supportsPrompt: true,
    supportsFileUpload: true,
    supportsMask: false,
  },
  'generate-background': {
    id: 'generate-background',
    name: 'Generate Background',
    description: 'Use a mask to generate a new background for the unmasked subject.',
    icon: 'image-plus',
    route: '/edit/generate-background',
    category: 'edit',
    supportedModels: ['recraftv4', 'recraftv3'],
    creditsPerGeneration: 40,
    supportsPrompt: true,
    supportsFileUpload: true,
    supportsMask: true,
  },
  'erase-region': {
    id: 'erase-region',
    name: 'Erase Region',
    description: 'Remove unwanted objects or flaws from a specific masked area.',
    icon: 'eraser',
    route: '/edit/erase-region',
    category: 'edit',
    supportedModels: ['recraftv4', 'recraftv3'],
    creditsPerGeneration: 2,
    supportsPrompt: false,
    supportsFileUpload: true,
    supportsMask: true,
  },
  vectorize: {
    id: 'vectorize',
    name: 'Vectorize Image',
    description: 'Convert raster images to clean SVG vectors ready for design tools.',
    icon: 'vector',
    route: '/tools/vectorize',
    category: 'tool',
    supportedModels: ['recraftv4', 'recraftv3'],
    creditsPerGeneration: 10,
    supportsPrompt: false,
    supportsFileUpload: true,
    supportsMask: false,
  },
  'remove-background': {
    id: 'remove-background',
    name: 'Remove Background',
    description: 'Instantly strip backgrounds from any subject with high precision.',
    icon: 'scissors',
    route: '/tools/remove-background',
    category: 'tool',
    supportedModels: ['recraftv4', 'recraftv3'],
    creditsPerGeneration: 10,
    supportsPrompt: false,
    supportsFileUpload: true,
    supportsMask: false,
  },
  upscale: {
    id: 'upscale',
    name: 'Upscale',
    description: 'Enhance resolution using Crisp or Creative models.',
    icon: 'maximize',
    route: '/tools/upscale',
    category: 'tool',
    supportedModels: ['recraftv4', 'recraftv3'],
    creditsPerGeneration: 4,
    supportsPrompt: false,
    supportsFileUpload: true,
    supportsMask: false,
  },
  remix: {
    id: 'remix',
    name: 'Remix Image',
    description: 'Generate a conceptually similar variation of your image.',
    icon: 'shuffle',
    route: '/tools/remix',
    category: 'tool',
    supportedModels: ['recraftv4', 'recraftv3'],
    creditsPerGeneration: 40,
    supportsPrompt: false,
    supportsFileUpload: true,
    supportsMask: false,
  },
  explore: {
    id: 'explore',
    name: 'Explore',
    description: 'Discover diverse stylistic generations from a single prompt.',
    icon: 'compass',
    route: '/explore',
    category: 'generate',
    supportedModels: ['recraftv4'],
    creditsPerGeneration: 40,
    supportsPrompt: true,
    supportsFileUpload: false,
    supportsMask: false,
  }
};

export const TOOLS_LIST = Object.values(TOOLS);
